// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VetAwesome.Seeder.Database;

public partial class Appointment
{
    public int Id { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int PetId { get; set; }

    public int VeterinarianId { get; set; }

    public virtual Pet Pet { get; set; }

    public virtual User Veterinarian { get; set; }
}