// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VetAwesome.Seeder.Database;

public partial class PetBreed
{
    public int Id { get; set; }

    public int PetTypeId { get; set; }

    public string Name { get; set; }

    public virtual PetType PetType { get; set; }

    public virtual ICollection<Pet> Pets { get; set; } = new List<Pet>();
}