// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VetAwesome.Seeder.Database;

public partial class Address
{
    public int Id { get; set; }

    public string StreetAddress { get; set; }

    public string City { get; set; }

    public string ZipCode { get; set; }

    public int StateId { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual State State { get; set; }
}