// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VetAwesome.Seeder.Database;

public partial class PetType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<PetBreed> PetBreeds { get; set; } = new List<PetBreed>();
}