drop table if exists Appointment
drop table if exists Pet
drop table if exists PetBreed
drop table if exists PetType
drop table if exists Customer
drop table if exists Address
drop table if exists [State]
drop table if exists [User]
drop table if exists UserRole
